name: strike_cli
description: A dart CLI task runner.
version: 0.7.2
repository: https://github.com/Stumblinbear/strike_cli

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  path: ^1.8.0

  yaml: ^3.1.1
  args: ^2.3.1
  glob: ^2.1.1

  dart_console: ^1.1.2

executables:
  strike: strike_cli
